name: dart_aliyun_oss
description: Dart client SDK for Alibaba Cloud Object Storage Service (OSS). Supports file upload, download, multipart upload, signed URLs and more.
version: 1.0.4
homepage: https://github.com/lvyandev/ali_yun_oss
repository: https://github.com/lvyandev/ali_yun_oss
issue_tracker: https://github.com/lvyandev/ali_yun_oss/issues

# License
license: MIT

# Keywords for search
keywords:
  - aliyun
  - alibaba
  - alibaba cloud
  - oss
  - object storage
  - cloud storage
  - storage
  - upload
  - download
  - multipart
  - file
  - signed url
  - presigned
  - s3

# Topics for pub.dev
topics:
  - storage
  - cloud
  - file
  - network
  - api

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  convert: ^3.1.1
  crypto: ^3.0.6
  dio: ^5.8.0+1

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15